allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
dedupePeers: true
minimumReleaseAge: 10080
provenance: true
savePrefix: =
strictPeerDependencies: true
