default_install_hook_types = ["post-checkout", "post-merge", "post-rewrite", "pre-commit", "pre-push"]

[[repos]]
repo = "builtin"
hooks = [
  { id = "trailing-whitespace" },
  { id = "check-added-large-files" },
  { id = "check-case-conflict" },
  { id = "check-executables-have-shebangs" },
  { id = "check-illegal-windows-names" },
  { id = "check-json5" },
  { id = "check-jsonc", args = [
    "--allow-trailing-commas",
  ], files = "^\\.vscode\\/[^/]+\\.json$", types = [
    "json",
  ] },
  { id = "check-merge-conflict" },
  { id = "check-merge-conflict", args = [
    "--assume-in-merge",
  ] },
  { id = "check-shebang-scripts-are-executable" },
  { id = "check-symlinks" },
  { id = "check-toml" },
  { id = "check-vcs-permalinks" },
  { id = "check-xml" },
  { id = "check-yaml", args = [
    "--allow-multiple-documents",
  ] },
  { id = "destroyed-symlinks" },
  { id = "detect-private-key" },
  { id = "end-of-file-fixer" },
  { id = "fix-byte-order-marker" },
  { id = "forbid-new-submodules" },
  { id = "mixed-line-ending" },
  { id = "trailing-whitespace" },
]

[[repos]]
repo = "https://github.com/crate-ci/typos"
rev = "53821664afd79bb88fcdd22fdc2f49d8d3f6cac9" # frozen: v1
hooks = [{ id = "typos" }]

[[repos]]
repo = "https://github.com/gitleaks/gitleaks"
rev = "83d9cd684c87d95d656c1458ef04895a7f1cbd8e" # frozen: v8.30.1
hooks = [{ id = "gitleaks" }]

[[repos]]
repo = "https://github.com/oxc-project/mirrors-oxlint"
rev = "be81c102ec0488fa738ccb960c1d7711eb295a70" # frozen: v1.82.0
hooks = [{ id = "oxlint" }]

[[repos]]
repo = "https://github.com/oxc-project/mirrors-oxfmt"
rev = "e2ce5b75f17181f7f786b41b83be1dc330c73df4" # frozen: v0.67.0
hooks = [{ id = "oxfmt" }]

[[repos]]
repo = "local"
hooks = [
  { id = "eslint", name = "eslint", language = "system", entry = "pnpm prek:eslint", groups = [
    "local",
  ], types_or = [
    "html",
    "javascript",
    "ts",
  ] },
  { id = "prettier", name = "prettier", language = "system", entry = "pnpm prek:prettier", groups = [
    "local",
  ], types_or = [
    "html",
  ] },
  { id = "pnpm-sync", name = "pnpm-sync", language = "system", entry = "pnpm install", groups = [
    "local",
  ], pass_filenames = false },
]
